// Nova - Python Figure Integration for Typst
//
// This module provides the `pyplot()` function for embedding Python-generated
// figures (matplotlib, seaborn, plotly, etc.) in Typst documents.
//
// Usage:
//   #import "@local/nova:0.1.0": pyplot
//
//   // As a figure with caption and label
//   #figure(
//     pyplot("sine-wave", width: 80%),
//     caption: [A sine wave]
//   ) <fig:sine>
//
//   // Inline without figure wrapper
//   The result is shown here: #pyplot("results", width: 50%)

/// The default cache directory for generated figures.
/// This file is provisioned to `.nova/pyplot.typ`, so paths are resolved
/// relative to `.nova/`. Use `"cache"` (not `".nova/cache"`) to avoid
/// path doubling (`.nova/.nova/cache/...`).
#let nova-cache-dir = "cache"

/// Load a Python-generated plot by name.
///
/// This function loads an SVG figure generated by a Python function
/// decorated with `@nova.figure("name")`. The figure is retrieved
/// from the nova cache directory.
///
/// Arguments:
/// - name: The figure name (string) as specified in the @nova.figure decorator
/// - width: Optional width (default: auto)
/// - height: Optional height (default: auto)
/// - fit: How to fit the image ("cover", "contain", "stretch") (default: "contain")
/// - alt: Alternative text for accessibility (default: auto-generated)
///
/// Returns:
/// - An image element containing the generated SVG
///
/// Example:
///   ```typst
///   // Simple inline usage
///   #pyplot("results-plot", width: 80%)
///
///   // As a numbered figure
///   #figure(
///     pyplot("architecture-diagram"),
///     caption: [System architecture]
///   ) <fig:arch>
///   ```
#let pyplot(
  name,
  width: auto,
  height: auto,
  fit: "contain",
  alt: auto,
) = {
  // Construct the path to the cached SVG
  let svg-path = nova-cache-dir + "/" + name + ".svg"

  // Auto-generate alt text if not provided
  let alt-text = if alt == auto {
    "Python figure: " + name
  } else {
    alt
  }

  // Return an image element
  image(
    svg-path,
    width: width,
    height: height,
    fit: fit,
    alt: alt-text,
  )
}

/// Load a Python-generated plot with custom cache directory.
///
/// Use this if your project uses a non-standard cache location.
///
/// Arguments:
/// - name: The figure name
/// - cache-dir: Path to the cache directory
/// - width, height, fit, alt: Same as `pyplot()`
#let pyplot-from(
  name,
  cache-dir,
  width: auto,
  height: auto,
  fit: "contain",
  alt: auto,
) = {
  let svg-path = cache-dir + "/" + name + ".svg"

  let alt-text = if alt == auto {
    "Python figure: " + name
  } else {
    alt
  }

  image(
    svg-path,
    width: width,
    height: height,
    fit: fit,
    alt: alt-text,
  )
}
